### ISSUE TITLE
Help running the model

### ISSUE THREAD

**Issue by fdesales** [ObbeTuinenburg/U-Track#2]
Hello.  Thank you for sharing the UTrack model code.

I am trying to get the model to run and have a few questions.  I used the `get_ERA5.py` script to download the ERA5 forcing data.  The variables downloaded are uv, w, q, and EP.  When I try to run the model, I get several "No such file or directory" error messages.  It seems I do not have all the variables I need.

I noticed that the `read.c` routine also reads other variables, such as p72.162, tcw and t, which are not downloaded by the `get_ERA5.py script`.

Are these additional variables really necessary to run the model?  If they are, can you help me figure out how to download then from the Copernicus database?

Thank you for your help.

**Comment by KAMurph** [comment]
Hello. Were you able to figure out this issue? I am at this point now. 

Thank you.

**Comment by fdesales** [comment]
Hi. I asked the question for a student of mine at that time, and I don't think we ever figured out a solution. The student moved on with another modeling approach.  Good luck to you.
